### ISSUE TITLE
Jetson_Nano: Could not pull image mcr.microsoft.com/azureiotedge/sqlite:1.0

### ISSUE THREAD

**Issue by orionJag** [Azure/iot-edge-sqlite#11]
Hi
   I am trying to run a sqlite module on the Jetson Nano & it's failing with the following msg.  Need some directions on how to resolve this.

> <6> 2021-01-29 13:29:09.439 +00:00 [INF] - Executing command: "Command Group: (\n  [Create module SQLiteJetson]\n  [Start module SQLiteJetson]\n)"
> <6> 2021-01-29 13:29:09.439 +00:00 [INF] - Executing command: "Create module SQLiteJetson"
> <3> 2021-01-29 13:29:26.735 +00:00 [ERR] - Executing command for operation ["create"] failed.
> Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling Create module SQLiteJetson: Could not create module SQLiteJetson
> 	caused by: Could not pull image mcr.microsoft.com/azureiotedge/sqlite:1.0
> 	caused by: no matching manifest for linux/arm64/v8 in the manifest list entries, StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2020_07_07.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs:line 232
>    at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 143
>    at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2020_07_07.ModuleManagementHttpClient.CreateModuleAsync(ModuleSpec moduleSpec) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs:line 100
>    at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 59
> <3> 2021-01-29 13:29:26.740 +00:00 [ERR] - Executing command for operation ["Command Group: (\n  [Create module SQLiteJetson]\n  [Start module SQLiteJetson]\n)"] failed.
> Microsoft.Azure.Devices.Edge.Agent.Edgelet.EdgeletCommunicationException- Message:Error calling Create module SQLiteJetson: Could not create module SQLiteJetson
> 	caused by: Could not pull image mcr.microsoft.com/azureiotedge/sqlite:1.0
> 	caused by: no matching manifest for linux/arm64/v8 in the manifest list entries, StatusCode:500, at:   at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2020_07_07.ModuleManagementHttpClient.HandleException(Exception exception, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs:line 232
>    at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Versioning.ModuleManagementHttpClientVersioned.Execute[T](Func`1 func, String operation) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs:line 143
>    at Microsoft.Azure.Devices.Edge.Agent.Edgelet.Version_2020_07_07.ModuleManagementHttpClient.CreateModuleAsync(ModuleSpec moduleSpec) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs:line 100
>    at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 59
>    at Microsoft.Azure.Devices.Edge.Agent.Core.Commands.GroupCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/commands/GroupCommand.cs:line 35
>    at Microsoft.Azure.Devices.Edge.Agent.Core.LoggingCommandFactory.LoggingCommand.ExecuteAsync(CancellationToken token) in /home/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/LoggingCommandFactory.cs:line 59
> <3> 2021-01-29 13:29:26.744 +00:00 [ERR] - Step failed in deployment 56, continuing execution. Failure when running command Command Group: (
>   [Create module SQLiteJetson]
>   [Start module SQLiteJetson]
> ). Will retry in -03s.
> 

Also, tried the docker pull
    $ docker pull mcr.microsoft.com/azureiotedge/sqlite
    Using default tag: latest
    latest: Pulling from azureiotedge/sqlite
    no matching manifest for linux/arm64/v8 in the manifest list entries

OS info
Jetpack: 4.4.1 [L4T 32.4.4]

Your help is highly appreciated.

**Comment by orionJag** [comment]
Confirmed that Jetson needs arm64v8, wondering anything at works towards this version ?

Thanks
